- name: Configuring mysql server
  hosts: mysql
  become: yes #sudo
  Vars:
   mysql_root_password: ExpenseApp@1
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: installed

# Start MySQL Service
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  # - name: Collect info about databases and version using ~/.my.cnf as a credential file
  #   community.mysql.mysql_info:
  #   filter:
  #   - databases
  #   - version
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}"
      # login_host: mysql.tuktukride.online



      